#!/bin/bash

# Get the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# Get the parent directory of the script
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

node "$PARENT_DIR/_build/compile.js" "$@"
