name: Test Joelang Compiler

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  LLVM_VERSION: 14.0.6
  LLVM_VERSION_MAJOR: 14
  PKG_TARGET: null
  JOEC_COMMAND: node _build/compile.js

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-12
        # - windows-2022
        node: [18]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        check-latest: true

    - name: Install LLVM
      uses: .github/actions/install-llvm
      with:
        llvm-version: ${{ env.LLVM_VERSION }}
        llvm-version-major: ${{ env.LLVM_VERSION_MAJOR }}
        os: ${{ matrix.os }}
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: |
        npm install
        npm install -g pkg

    - name: Build project and executable
      run: |
        npm run build
        pkg -t ${{ env.PKG_TARGET }} --output "${{ env.JOEC_COMMAND }}" _build/compile.js
        chmod +x ${{ env.JOEC_COMMAND }}

    - name: Run tests
      run: npx jest -- e2e.spec.js
